question_data = [
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "In the 1988 film 'Akira', Tetsuo ends up destroying Tokyo.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                           "question": "The Great Wall of China is visible from the moon.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Greenland is almost as big as Africa.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "The music video to The Buggle&#039;s 'Video Killed the Radio Star' was the first music video to broadcast on MTV.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Greenland is covered with grass and Iceland covered with ice.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                          "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In 'Super Mario 64', collecting 100 coins on a level will give you a 1-UP.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "The 'Berenstein Bears' is the correct spelling of the educational children&#039;s book series&#039; name.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "There is a city called Rome in every continent on Earth.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Luigi is taller than Mario?", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "The United States was a member of the League of Nations.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                          "question": "In the original script of 'The Matrix', the machines used humans as additional computing power instead of batteries.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Big the Cat is a playable character in 'Sonic Generations'.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                          "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
         "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Gordon Freeman, the protagonist of 'Half-Life', is said to have once had a ponytail.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The ultimate phrase used by Pharah from Overwatch is: 'Justice rains from above!'",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "There are no deserts in Europe.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
         "question": "The Angry Video Game Nerd&#039;s alter ego is 'Board James'.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In the 'Half-Life' series, 'H.E.V' stands for 'Hazardous Evasiveness Vest'",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "The name of the attack 'Kamehameha' in Dragon Ball Z was named after a famous king of Hawaii.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "George Lucas directed the entire original Star Wars trilogy.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
         "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was 'Yes We Can'.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "Stevie Wonder&#039;s real name is Stevland Hardaway Morris.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
                                           "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Pok&eacute;mon, Arbok evolves into Seviper.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                          "question": "'Minions' was released on the June 10th, 2015.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In RuneScape, one must complete the 'Dragon Slayer' quest before equipping Rune Platelegs.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Valve&#039;s 'Portal' and 'Half-Life' franchises exist within the same in-game universe.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "An average human can go two weeks without water.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Art", "type": "boolean", "difficulty": "easy",
                                          "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In 'Doctor Who', the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                                           "question": "The sum of any two odd integers is odd.",
                                           "correct_answer": "False",
                                           "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Scotland voted to become an independent country during the referendum from September 2014.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "Psychology is the science of behavior and mind.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                           "question": "Nova Scotia is on the east coast of Canada.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
         "question": "A scalene triangle has two sides of equal length.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "'The Simpsons' family is named after creator Matt Groening&#039;s real family.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The game 'Jetpack Joyride' was created by 'Redbrick Studios'.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel 'The Lord of The Rings'.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Tony Hawk&#039;s extreme sports videogames revolve around performing professional BMX tricks.",
         "correct_answer": "False", "incorrect_answers": ["True"]}
]